services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_manager_app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    networks:
      - task_net

  postgres:
    image: postgres:16-alpine
    container_name: task_manager_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - task_net

  redis:
    image: redis:7.2-alpine
    container_name: task_manager_redis
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - task_net

networks:
  task_net:
    driver: bridge

volumes:
  pg_data:
